<?php

declare(strict_types=1);

namespace SapB1\Toolkit\Enums;

enum ApprovalRequestStatusType: string
{
    case Pending = 'arstPending';
    case Approved = 'arstApproved';
    case NotApproved = 'arstNotApproved';
    case Generated = 'arstGenerated';
    case GeneratedByAuthorizer = 'arstGeneratedByAuthorizer';
    case Cancelled = 'arstCancelled';

    public function label(): string
    {
        return match ($this) {
            self::Pending => 'Pending',
            self::Approved => 'Approved',
            self::NotApproved => 'Not Approved',
            self::Generated => 'Generated',
            self::GeneratedByAuthorizer => 'Generated by Authorizer',
            self::Cancelled => 'Cancelled',
        };
    }

    public function isPending(): bool
    {
        return $this === self::Pending;
    }

    public function isApproved(): bool
    {
        return $this === self::Approved || $this === self::Generated || $this === self::GeneratedByAuthorizer;
    }
}
